name: Release Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    if:       "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Git Config
        run: |
          git config --global user.name $GITHUB_REPOSITORY_OWNER
          git config --global user.email $GITHUB_REPOSITORY_OWNER@users.noreply.github.com

      - name: Setup Node 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install NPM dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build
        run: |
          npm run build
          mv serenity-detox-*.tgz serenity-detox.tgz

      - uses: actions/upload-artifact@v3
        with:
          retention-days: 3
          path: serenity-detox.tgz

      - name: Push New Version
        run: |
          git push
          git push origin --tags

      - uses: nyaa8/package-version@v1

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: serenity-detox.tgz
